use std::{
    fs::{self, File},
    io::Write,
    path::{Path, PathBuf},
};

#[derive(Debug, Clone)]
pub struct ReportPaths {
    pub root: PathBuf,
    pub tables: PathBuf,
    pub figures: PathBuf,
}

impl ReportPaths {
    pub fn prepare(root: impl AsRef<Path>) -> std::io::Result<Self> {
        let root = root.as_ref().to_path_buf();
        let tables = root.join("tables");
        let figures = root.join("figures");

        fs::create_dir_all(&tables)?;
        fs::create_dir_all(&figures)?;

        Ok(Self { root, tables, figures })
    }

    pub fn table(&self, filename: &str) -> PathBuf {
        self.tables.join(filename)
    }

    pub fn figure(&self, filename: &str) -> PathBuf {
        self.figures.join(filename)
    }

    pub fn readme(&self) -> PathBuf {
        self.root.join("README.md")
    }
}

/// Writes the top-level generated reports index.
///
/// # Parameters
/// - `reports_dir`: Directory containing generated dataset report folders.
/// - `index_path`: Path to the top-level reports index file.
pub fn write_reports_index(
    reports_dir: impl AsRef<Path>,
    index_path: impl AsRef<Path>,
) -> std::io::Result<()> {
    let reports_dir = reports_dir.as_ref();

    fs::create_dir_all(reports_dir)?;

    let mut dataset_reports = Vec::new();

    for entry in fs::read_dir(reports_dir)? {
        let entry = entry?;

        if !entry.file_type()?.is_dir() {
            continue;
        }

        let dataset_name = entry.file_name().to_string_lossy().to_string();
        let dataset_readme = entry.path().join("README.md");

        if dataset_readme.exists() {
            dataset_reports.push(dataset_name);
        }
    }

    dataset_reports.sort();

    let mut file = File::create(index_path)?;

    writeln!(file, "# Generated reports")?;
    writeln!(file)?;
    writeln!(
        file,
        "This file is generated by `spectra-profiler-rs` and links to available dataset-level report indexes."
    )?;
    writeln!(file)?;
    writeln!(file, "## Dataset reports")?;
    writeln!(file)?;

    if dataset_reports.is_empty() {
        writeln!(file, "No dataset reports have been generated yet.")?;
        return Ok(());
    }

    writeln!(file, "| Dataset | Report |")?;
    writeln!(file, "|---|---|")?;

    for dataset_name in dataset_reports {
        writeln!(file, "| `{dataset_name}` | [Open](reports/{dataset_name}/README.md) |")?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prepares_report_directories() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path().join("reports").join("annotated_ms2").join("f");

        let reports = ReportPaths::prepare(&root).unwrap();

        assert_eq!(reports.root, root);
        assert!(reports.tables.exists());
        assert!(reports.figures.exists());
    }

    #[test]
    fn builds_table_figure_and_readme_paths() {
        let temp_dir = tempfile::tempdir().unwrap();
        let reports = ReportPaths::prepare(temp_dir.path().join("report")).unwrap();

        assert_eq!(reports.table("summary.csv"), reports.tables.join("summary.csv"));

        assert_eq!(reports.figure("plot.svg"), reports.figures.join("plot.svg"));

        assert_eq!(reports.readme(), reports.root.join("README.md"));
    }

    #[test]
    fn writes_top_level_reports_index() {
        let temp_dir = tempfile::tempdir().unwrap();
        let reports_dir = temp_dir.path().join("reports");
        let index_path = temp_dir.path().join("REPORTS.md");

        let annotated = reports_dir.join("annotated_ms2");
        let local = reports_dir.join("local_dataset");

        std::fs::create_dir_all(&annotated).unwrap();
        std::fs::create_dir_all(&local).unwrap();

        std::fs::write(annotated.join("README.md"), "# annotated_ms2").unwrap();
        std::fs::write(local.join("README.md"), "# local_dataset").unwrap();

        write_reports_index(&reports_dir, &index_path).unwrap();

        let contents = std::fs::read_to_string(index_path).unwrap();

        assert!(contents.contains("# Generated reports"));
        assert!(contents.contains("[Open](reports/annotated_ms2/README.md)"));
        assert!(contents.contains("[Open](reports/local_dataset/README.md)"));
    }
}
